server:
  port: 8082

spring:
  application:
    name: ListWorkers
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
